# Generated by Django 5.2.8 on 2025-12-16 12:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_cnpj_nullable'),
        ('titulares', '0014_remove_dependente_dependente_id_naci_ac7402_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPrestadora',
            fields=[
                ('id', models.UUIDField(db_column='id_empresa_prestadora', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('nome_juridico', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_prestadoras_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_prestadoras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Empresa Prestadora',
                'verbose_name_plural': 'Empresas Prestadoras',
                'db_table': 'empresa_prestadora',
                'ordering': ['nome_fantasia', 'nome_juridico'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.UUIDField(db_column='id_ordem_servico', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data da OS')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO', 'Aguardando'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor dos Serviços')),
                ('valor_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor das Despesas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa_pagadora', models.ForeignKey(db_column='id_empresa_pagadora', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_pagas', to='empresa.empresa', verbose_name='Empresa Pagadora')),
                ('empresa_prestadora', models.ForeignKey(db_column='id_empresa_prestadora', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_prestadas', to='ordem_servico.empresaprestadora', verbose_name='Empresa Prestadora')),
                ('empresa_solicitante', models.ForeignKey(db_column='id_empresa_solicitante', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_solicitadas', to='empresa.empresa', verbose_name='Empresa Solicitante')),
                ('responsavel', models.ForeignKey(blank=True, db_column='id_responsavel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'ordem_servico',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.UUIDField(db_column='id_despesa', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('HOSPEDAGEM', 'Hospedagem'), ('TAXA', 'Taxa'), ('DOCUMENTACAO', 'Documentação'), ('TRADUCAO', 'Tradução'), ('CARTORIO', 'Cartório'), ('CORREIO', 'Correio'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'db_table': 'despesa',
                'ordering': ['tipo', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoDependente',
            fields=[
                ('id', models.UUIDField(db_column='id_ordem_servico_dependente', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_dependentes_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_dependentes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('dependente', models.ForeignKey(db_column='id_dependente', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='titulares.dependente', verbose_name='Dependente')),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_vinculados', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Dependente da OS',
                'verbose_name_plural': 'Dependentes da OS',
                'db_table': 'ordem_servico_dependente',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoTitular',
            fields=[
                ('id', models.UUIDField(db_column='id_ordem_servico_titular', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_titulares_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_titulares_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='titulares_vinculados', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
                ('titular', models.ForeignKey(db_column='id_titular', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='titulares.titular', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Titular da OS',
                'verbose_name_plural': 'Titulares da OS',
                'db_table': 'ordem_servico_titular',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(db_column='id_servico', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item/Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'servico',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='ServicoContratado',
            fields=[
                ('id', models.UUIDField(db_column='id_servico_contratado', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do serviço. Se vazio, usa o valor base do catálogo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_contratados_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_contratados_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', help_text='Empresa beneficiária do serviço (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos_contratados', to='empresa.empresa', verbose_name='Empresa Beneficiária')),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
                ('servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='ordem_servico.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço Contratado',
                'verbose_name_plural': 'Serviços Contratados',
                'db_table': 'servico_contratado',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['numero'], name='ordem_servi_numero_30e047_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status'], name='ordem_servi_status_0bb350_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['data'], name='ordem_servi_data_4531fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemservicodependente',
            unique_together={('ordem_servico', 'dependente')},
        ),
        migrations.AlterUniqueTogether(
            name='ordemservicotitular',
            unique_together={('ordem_servico', 'titular')},
        ),
    ]
