# Generated by Django 5.2.8 on 2025-12-16 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de despesas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='servicocontratado',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de serviços contratados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
    ]
