# Generated by Django 5.2.8 on 2025-12-16 22:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresa', '0003_cnpj_nullable'),
        ('ordem_servico', '0002_despesa_quantidade_servicocontratado_quantidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id', models.UUIDField(db_column='id_ordem_servico_item', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, help_text='Valor aplicado nesta OS (herda do contrato por padrão)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Aplicado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Item da OS',
                'verbose_name_plural': 'Itens da OS',
                'db_table': 'ordem_servico_item',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='empresa_prestadora',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='contrato',
            field=models.ForeignKey(db_column='id_contrato', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='contratos.contrato', verbose_name='Contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='empresa_pagadora',
            field=models.ForeignKey(db_column='id_empresa_pagadora', help_text='Empresa responsável pelo pagamento', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_pagas', to='empresa.empresa', verbose_name='Empresa Pagadora'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='empresa_solicitante',
            field=models.ForeignKey(db_column='id_empresa_solicitante', help_text='Empresa que solicita o serviço (pode ser diferente da contratante)', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_solicitadas', to='empresa.empresa', verbose_name='Empresa Solicitante'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['contrato'], name='ordem_servi_id_cont_1e837a_idx'),
        ),
        migrations.AddField(
            model_name='ordemservicoitem',
            name='contrato_servico',
            field=models.ForeignKey(db_column='id_contrato_servico', on_delete=django.db.models.deletion.PROTECT, related_name='itens_os', to='contratos.contratoservico', verbose_name='Serviço do Contrato'),
        ),
        migrations.AddField(
            model_name='ordemservicoitem',
            name='ordem_servico',
            field=models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço'),
        ),
        migrations.DeleteModel(
            name='ServicoContratado',
        ),
    ]
