# Generated by Django 5.2.8 on 2025-12-20 14:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.UUIDField(db_column='id_tipo_despesa', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item/Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_despesa_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_despesa_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesa',
                'db_table': 'tipo_despesa',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='DespesaOrdemServico',
            fields=[
                ('id', models.UUIDField(db_column='id_despesa_ordem_servico', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor aplicado (herda do tipo de despesa por padrão)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_os_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_os_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
                ('tipo_despesa', models.ForeignKey(db_column='id_tipo_despesa', on_delete=django.db.models.deletion.PROTECT, related_name='despesas_os', to='ordem_servico.tipodespesa', verbose_name='Tipo de Despesa')),
            ],
            options={
                'verbose_name': 'Despesa da OS',
                'verbose_name_plural': 'Despesas da OS',
                'db_table': 'despesa_ordem_servico',
                'ordering': ['tipo_despesa__item', 'data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
    ]
