# Generated by Django 5.2.8 on 2025-12-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0005_alter_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateField(verbose_name='Data de Abertura'),
        ),
    ]
