# Generated by Django 5.2.9 on 2026-01-03 05:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0006_alter_ordemservico_data_abertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoOS',
            fields=[
                ('id', models.UUIDField(db_column='id_documento_os', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código do Documento')),
                ('hash_sha256', models.CharField(editable=False, help_text='Hash criptográfico do conteúdo do PDF para validação', max_length=64, verbose_name='Hash SHA-256')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da geração do documento (UTC-3)', verbose_name='Data de Emissão')),
                ('dados_snapshot', models.JSONField(default=dict, help_text='Cópia dos dados da OS no momento da emissão', verbose_name='Snapshot dos Dados')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('emitido_por', models.ForeignKey(blank=True, db_column='emitido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_os_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Documento de OS',
                'verbose_name_plural': 'Documentos de OS',
                'db_table': 'documento_os',
                'ordering': ['-data_emissao'],
                'unique_together': {('ordem_servico', 'versao')},
            },
        ),
    ]
