# Generated by Django 5.2.9 on 2026-01-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0007_documentoos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoos',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='documentoos',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='documentoos',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código do Documento'),
        ),
        migrations.AlterField(
            model_name='documentoos',
            name='hash_sha256',
            field=models.CharField(help_text='Hash criptográfico do conteúdo do PDF para validação', max_length=64, verbose_name='Hash SHA-256'),
        ),
    ]
