# Generated by Django 5.2.9 on 2026-01-11 03:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0009_alter_os_status_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_column='id_responsavel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_solicitante', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='valor_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor base de referência (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Base'),
        ),
    ]
