# Generated by Django 5.2.9 on 2026-01-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0010_make_valor_base_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='item',
            field=models.CharField(max_length=50, unique=True, verbose_name='Item/Código'),
        ),
    ]
