# Generated by Django 5.2.8 on 2025-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_data_registro_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
