# Generated by Django 5.2.8 on 2025-11-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dependente',
            new_name='dependente_id_titu_cdff39_idx',
            old_name='dependente_id_titu_a27e31_idx',
        ),
        migrations.RenameIndex(
            model_name='dependente',
            new_name='dependente_passapo_7e565a_idx',
            old_name='dependente_passapo_3f14d7_idx',
        ),
        migrations.RenameIndex(
            model_name='dependente',
            new_name='dependente_id_naci_ac7402_idx',
            old_name='dependente_id_naci_30a923_idx',
        ),
        migrations.RenameIndex(
            model_name='titular',
            new_name='titular_nome_c450f5_idx',
            old_name='titular_nome_4e67cb_idx',
        ),
        migrations.RenameIndex(
            model_name='titular',
            new_name='titular_id_naci_a8d111_idx',
            old_name='titular_id_naci_f8f63c_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculotitular',
            new_name='vinculo_tit_id_titu_57545a_idx',
            old_name='vinculo_tit_id_titu_a3f9ce_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculotitular',
            new_name='vinculo_tit_tipo_vi_f5ae2f_idx',
            old_name='vinculo_tit_tipo_vi_d0dbdd_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculotitular',
            new_name='vinculo_tit_status_732b6a_idx',
            old_name='vinculo_tit_status_cfe56e_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculotitular',
            new_name='vinculo_tit_id_empr_b32f28_idx',
            old_name='vinculo_tit_id_empr_e8de7e_idx',
        ),
        migrations.RenameIndex(
            model_name='vinculotitular',
            new_name='vinculo_tit_data_fi_02b123_idx',
            old_name='vinculo_tit_data_fi_e22556_idx',
        ),
    ]
