# Generated by Django 5.2.8 on 2025-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0002_rename_dependente_id_titu_a27e31_idx_dependente_id_titu_cdff39_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculotitular',
            name='tipo_vinculo',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('PARTICULAR', 'Particular'), ('CONSULADO', 'Consulado'), ('AUTONOMO', 'Autônomo'), ('ESTUDANTE', 'Estudante'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Vínculo'),
        ),
    ]
