# Generated by Django 5.2.8 on 2025-12-02 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('titulares', '0003_alter_vinculotitular_tipo_vinculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoDependente',
            fields=[
                ('id', models.UUIDField(db_column='id_vinculo', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('data_fim_vinculo', models.DateField(blank=True, null=True, verbose_name='Data Fim do Vínculo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('amparo', models.ForeignKey(blank=True, db_column='id_amparo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_dependentes', to='core.amparolegal', verbose_name='Amparo Legal')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_dependentes_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('consulado', models.ForeignKey(blank=True, db_column='id_consulado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_dependentes', to='core.consulado', verbose_name='Consulado')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_dependentes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('dependente', models.ForeignKey(db_column='id_dependente', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='titulares.dependente', verbose_name='Dependente')),
                ('tipo_atualizacao', models.ForeignKey(blank=True, db_column='id_tipo_atualizacao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_dependentes', to='core.tipoatualizacao', verbose_name='Tipo de Atualização')),
            ],
            options={
                'verbose_name': 'Vínculo do Dependente',
                'verbose_name_plural': 'Vínculos dos Dependentes',
                'db_table': 'vinculo_dependente',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['dependente'], name='vinculo_dep_id_depe_9406b0_idx'), models.Index(fields=['status'], name='vinculo_dep_status_d1fc66_idx'), models.Index(fields=['data_fim_vinculo'], name='vinculo_dep_data_fi_b2e7b7_idx'), models.Index(fields=['amparo'], name='vinculo_dep_id_ampa_eb5818_idx'), models.Index(fields=['consulado'], name='vinculo_dep_id_cons_1a3722_idx'), models.Index(fields=['tipo_atualizacao'], name='vinculo_dep_id_tipo_541219_idx')],
            },
        ),
    ]
