# Generated by Django 5.2.8 on 2025-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0004_add_vinculo_dependente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='data_validade_passaporte',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Passaporte'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='visto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visto'),
        ),
        migrations.AddField(
            model_name='titular',
            name='data_validade_passaporte',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Passaporte'),
        ),
        migrations.AddField(
            model_name='titular',
            name='visto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visto'),
        ),
        migrations.AddField(
            model_name='vinculodependente',
            name='tipo_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Status'),
        ),
        migrations.AddField(
            model_name='vinculotitular',
            name='tipo_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Status'),
        ),
    ]
