# Generated by Django 5.2.8 on 2025-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0005_add_visto_cnh_validade_passaporte_tipo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='ctps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CTPS'),
        ),
        migrations.AddField(
            model_name='titular',
            name='ctps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CTPS'),
        ),
    ]
