# Generated by Django 5.2.8 on 2025-12-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('titulares', '0006_add_ctps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='nacionalidade',
            field=models.ForeignKey(blank=True, db_column='id_nacionalidade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulares', to='core.nacionalidade', verbose_name='Nacionalidade'),
        ),
    ]
