# Generated by Django 5.2.8 on 2025-12-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0007_nacionalidade_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependente',
            old_name='visto',
            new_name='status_visto',
        ),
        migrations.RenameField(
            model_name='titular',
            old_name='visto',
            new_name='status_visto',
        ),
    ]
