# Generated by Django 5.2.8 on 2025-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0008_rename_visto_to_status_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='status_visto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status do Visto'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='rnm',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='RNM'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='status_visto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status do Visto'),
        ),
    ]
