# Generated by Django 5.2.8 on 2025-12-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0009_rnm_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculodependente',
            name='atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Atualização'),
        ),
        migrations.AddField(
            model_name='vinculotitular',
            name='atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Atualização'),
        ),
    ]
