# Generated by Django 5.2.8 on 2025-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0010_add_atualizacao_vinculos'),
    ]

    operations = [
        # Renomear campos no Titular
        migrations.RenameField(
            model_name='titular',
            old_name='pai',
            new_name='filiacao_um',
        ),
        migrations.RenameField(
            model_name='titular',
            old_name='mae',
            new_name='filiacao_dois',
        ),
        # Renomear campos no Dependente
        migrations.RenameField(
            model_name='dependente',
            old_name='pai',
            new_name='filiacao_um',
        ),
        migrations.RenameField(
            model_name='dependente',
            old_name='mae',
            new_name='filiacao_dois',
        ),
        # Atualizar verbose_name dos campos
        migrations.AlterField(
            model_name='titular',
            name='filiacao_um',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filiação 1'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='filiacao_dois',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filiação 2'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='filiacao_um',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filiação 1'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='filiacao_dois',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filiação 2'),
        ),
    ]
