# Generated by Django 5.2.8 on 2025-12-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0011_rename_pai_mae_to_filiacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
