# Generated by Django 5.2.8 on 2025-12-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0013_replace_nacionalidade_consulado_with_text'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dependente',
            name='dependente_id_naci_ac7402_idx',
        ),
        migrations.RemoveIndex(
            model_name='titular',
            name='titular_id_naci_a8d111_idx',
        ),
        migrations.RemoveIndex(
            model_name='vinculodependente',
            name='vinculo_dep_id_cons_1a3722_idx',
        ),
    ]
