# Generated by Django 5.2.8 on 2025-12-16 22:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_cnpj_nullable'),
        ('ordem_servico', '0002_despesa_quantidade_servicocontratado_quantidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(db_column='id_contrato', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa_contratante', models.ForeignKey(db_column='id_empresa_contratante', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_contratante', to='empresa.empresa', verbose_name='Empresa Contratante')),
                ('empresa_prestadora', models.ForeignKey(db_column='id_empresa_prestadora', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='ordem_servico.empresaprestadora', verbose_name='Empresa Prestadora')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ContratoServico',
            fields=[
                ('id', models.UUIDField(db_column='id_contrato_servico', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor negociado para este serviço neste contrato', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Contratado')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade prevista de serviços no contrato', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, db_column='atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_servicos_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to='contratos.contrato', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_servicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_servicos', to='ordem_servico.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do Contrato',
                'verbose_name_plural': 'Serviços do Contrato',
                'db_table': 'contrato_servico',
                'ordering': ['servico__item'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['numero'], name='contrato_numero_5056f5_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['status'], name='contrato_status_57ea48_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['data_inicio'], name='contrato_data_in_3ea635_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['data_fim'], name='contrato_data_fi_4ceedd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contratoservico',
            unique_together={('contrato', 'servico')},
        ),
    ]
