# Generated by Django 5.2.8 on 2025-12-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoservico',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='contratoservico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor negociado para este serviço neste contrato', max_digits=12, null=True, verbose_name='Valor Contratado'),
        ),
    ]
