# Generated by Django 5.2.9 on 2026-01-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_add_contratada_prazo_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato'), ('PROPOSTA', 'Proposta')], default='CONTRATO', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Contrato'),
        ),
    ]
