# Generated by Django 5.2.8 on 2025-12-12 23:53

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(db_column='id_departamento', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(choices=[('prazos', 'Sistema de Prazos'), ('ordem_servico', 'Ordens de Serviço')], help_text='Identificador único do sistema', max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('icone', models.CharField(default='📁', help_text='Emoji ou classe de ícone', max_length=50, verbose_name='Ícone')),
                ('cor', models.CharField(default='#3b82f6', help_text='Cor tema do sistema', max_length=20, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsuarioDepartamento',
            fields=[
                ('id', models.UUIDField(db_column='id_usuario_departamento', db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], default='consultor', max_length=20, verbose_name='Cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Última Atualização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_column='id_departamento', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.departamento', verbose_name='Departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Vínculo Usuário-Departamento',
                'verbose_name_plural': 'historical Vínculos Usuário-Departamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UsuarioDepartamento',
            fields=[
                ('id', models.UUIDField(db_column='id_usuario_departamento', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], default='consultor', max_length=20, verbose_name='Cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuario', to='accounts.departamento', verbose_name='Departamento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_departamento', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Departamento',
                'verbose_name_plural': 'Vínculos Usuário-Departamento',
                'db_table': 'usuario_departamento',
                'ordering': ['departamento__ordem', 'departamento__nome'],
                'unique_together': {('usuario', 'departamento')},
            },
        ),
    ]
