# Generated by Django 5.2.8 on 2025-12-13 00:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_departamentos_e_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(db_column='id_cargo', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], help_text='Identificador único do cargo', max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('nivel', models.PositiveIntegerField(default=1, help_text='Nível hierárquico (1=menor, 3=maior)', verbose_name='Nível')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nivel', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.UUIDField(db_column='id_sistema', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(choices=[('prazos', 'Sistema de Prazos'), ('ordem_servico', 'Ordens de Serviço')], help_text='Identificador único do sistema', max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('icone', models.CharField(default='📁', help_text='Emoji ou classe de ícone', max_length=50, verbose_name='Ícone')),
                ('cor', models.CharField(default='#3b82f6', help_text='Cor tema do sistema', max_length=20, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'db_table': 'sistema',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicalusuariodepartamento',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vínculo Legado (DEPRECATED)', 'verbose_name_plural': 'historical Vínculos Legados (DEPRECATED)'},
        ),
        migrations.AlterModelOptions(
            name='usuariodepartamento',
            options={'verbose_name': 'Vínculo Legado (DEPRECATED)', 'verbose_name_plural': 'Vínculos Legados (DEPRECATED)'},
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='cor',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(choices=[('consular', 'Consular'), ('juridico', 'Jurídico'), ('ti', 'Tecnologia da Informação'), ('rh', 'Recursos Humanos'), ('financeiro', 'Financeiro'), ('diretoria', 'Diretoria')], help_text='Identificador único do departamento', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='icone',
            field=models.CharField(default='🏢', help_text='Emoji ou classe de ícone', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(db_column='ativo', default=True, help_text='Indica se o usuário está ativo.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='cargo',
            field=models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], default='consultor', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='data_criacao',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='departamento',
            field=models.ForeignKey(blank=True, db_column='id_departamento', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.departamento'),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalusuariodepartamento',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='ativo', default=True, help_text='Indica se o usuário está ativo.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='cargo',
            field=models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], default='consultor', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='departamento',
            field=models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuario_legacy', to='accounts.departamento'),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuariodepartamento',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_departamento_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalUsuarioVinculo',
            fields=[
                ('id', models.UUIDField(db_column='id_usuario_vinculo', db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Última Atualização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_column='id_cargo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(blank=True, db_column='id_departamento', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.departamento', verbose_name='Departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('sistema', models.ForeignKey(blank=True, db_column='id_sistema', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.sistema', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'historical Vínculo de Acesso',
                'verbose_name_plural': 'historical Vínculos de Acesso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UsuarioVinculo',
            fields=[
                ('id', models.UUIDField(db_column='id_usuario_vinculo', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='accounts.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='accounts.departamento', verbose_name='Departamento')),
                ('sistema', models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='accounts.sistema', verbose_name='Sistema')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo de Acesso',
                'verbose_name_plural': 'Vínculos de Acesso',
                'db_table': 'usuario_vinculo',
                'ordering': ['sistema__ordem', 'departamento__ordem'],
                'unique_together': {('usuario', 'sistema', 'departamento')},
            },
        ),
    ]
