# Generated by Django 5.2.8 on 2025-12-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rbac_abac_hibrido'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, help_text='Permissões do Django herdadas por usuários com este cargo', related_name='cargos', to='auth.permission', verbose_name='Permissões'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='permissoes',
            field=models.ManyToManyField(blank=True, help_text='Permissões do Django herdadas por usuários deste departamento', related_name='departamentos', to='auth.permission', verbose_name='Permissões'),
        ),
    ]
