# Generated by Django 5.2.8 on 2025-12-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_permissions_to_cargo_departamento'),
        ('empresa', '0003_cnpj_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariovinculo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='historicalusuariovinculo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='historicalusuariodepartamento',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='historicalusuariodepartamento',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalusuariodepartamento',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='usuariodepartamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuariodepartamento',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuariodepartamento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='permissoes',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', db_constraint=False, help_text='Empresa do cliente (apenas para tipo_usuario=CLIENTE)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='tipo_usuario',
            field=models.CharField(choices=[('interno', 'Usuário Interno'), ('cliente', 'Cliente Externo')], default='interno', help_text='Define se é usuário interno ou cliente externo', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', help_text='Empresa do cliente (apenas para tipo_usuario=CLIENTE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('interno', 'Usuário Interno'), ('cliente', 'Cliente Externo')], default='interno', help_text='Define se é usuário interno ou cliente externo', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='HistoricalUsuarioDepartamento',
        ),
        migrations.DeleteModel(
            name='UsuarioDepartamento',
        ),
    ]
